pull_request_rules:
  - name: automatic merge when CultURIze import
    conditions:
      - author:@PACKED-vzw
      - base:master
      - title:Culturize Import
    actions:
      merge:
        method: merge
