version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run: 
          name: Copy files to webserver
          command: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "~/deploy.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters: 
            branches:
              only: master
