version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - run: echo "ik heb geen build" # run the `echo` command
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys: 
          fingerprints:
            - "33:8a:57:01:38:5f:38:a6:23:38:cc:43:4a:e2:ef:c6"
      - run: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "~/deploy.sh"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
